// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} target
 * @param {string} className
 * @returns {Promise.<void>}
 */
export async function ToggleClass(target, className) {
	// BEGIN USER CODE
	const myElement = document.querySelector(target);
	if (myElement) {
		myElement.classList.toggle(className);
	}
	return Promise.resolve();
	// END USER CODE
}
