// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function DeviceDisconnect() {
	// BEGIN USER CODE
	try{	
		return new Promise((resolve, reject) => {
			const gattServer = window.gattServer;
			if(gattServer && gattServer.connected){
				gattServer.disconnect();
			}
			resolve(true);
		});			
	} catch (error) {
		return Promise.reject(error);
	}
	// END USER CODE
}
