// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package taskqueuehelpers.actions;

import com.mendix.systemwideinterfaces.connectionbus.requests.types.IOQLTextGetRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.logging.ILogNode;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import java.util.List;
import java.util.HashMap;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTable;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataRow;

public class GetQueueCounts extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public GetQueueCounts(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext ctx = getContext();

		HashMap<String, IMendixObject> map = new HashMap<>();

		IOQLTextGetRequest oqlRequest = Core.createOQLTextGetRequest();
		oqlRequest.setQuery("SELECT QueueName, XASId FROM System.QueuedTask");
		IDataTable table = Core.retrieveOQLDataTable(ctx, oqlRequest);

		for (IDataRow row : table.getRows()) {
			String qname = row.getValue(ctx, 0);

			IMendixObject counts = map.computeIfAbsent(qname, key -> {
				IMendixObject newcounts = Core.instantiate(ctx, "TaskQueueHelpers.QueueCount");
				newcounts.setValue(getContext(), "QueueName", qname);
				return newcounts;
			});

			String xasId = row.getValue(ctx, 1);
			String countAttr = xasId == null ? "OpenCount" : "RunningCount";
			Long count = counts.getValue(ctx, countAttr);
			counts.setValue(ctx, countAttr, count + 1);

			map.put(qname, counts);
		}

		return map.values().stream().collect(Collectors.toList());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetQueueCounts";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
