// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapodataconnector.actions;

import org.apache.http.Consts;
import org.apache.http.HttpEntity;
import org.apache.http.client.entity.EntityBuilder;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.ContentType;
import org.apache.http.impl.client.CloseableHttpClient;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import sapodataconnector.proxies.constants.Constants;
import sapodataconnector.utils.ExpectedHttpResultOptional;
import sapodataconnector.utils.JsonSerializer;
import sapodataconnector.utils.ODataClientBuilder;
import sapodataconnector.utils.ODataRequestBuilder;
import sapodataconnector.utils.ODataResponseHandler;
import sapodataconnector.utils.ToMendixSerializer;

public class Create extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __odataObject;
	private sapodataconnector.proxies.OdataObject odataObject;
	private IMendixObject __destination;
	private sapodataconnector.proxies.Destination destination;
	private java.lang.String query;
	private IMendixObject __requestParameters;
	private sapodataconnector.proxies.RequestParams requestParameters;

	public Create(IContext context, IMendixObject odataObject, IMendixObject destination, java.lang.String query, IMendixObject requestParameters)
	{
		super(context);
		this.__odataObject = odataObject;
		this.__destination = destination;
		this.query = query;
		this.__requestParameters = requestParameters;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.odataObject = __odataObject == null ? null : sapodataconnector.proxies.OdataObject.initialize(getContext(), __odataObject);

		this.destination = __destination == null ? null : sapodataconnector.proxies.Destination.initialize(getContext(), __destination);

		this.requestParameters = __requestParameters == null ? null : sapodataconnector.proxies.RequestParams.initialize(getContext(), __requestParameters);

		// BEGIN USER CODE
		JSONObject json = JsonSerializer.writeMendixObjectToJson(getContext(), odataObject.getMendixObject(), true);
		String jsonStr = json.toString();

		if (LOGGER.isDebugEnabled()) {
			LOGGER.debug(new StringBuilder(getContext().getSession().getId().toString()).append("|CREATE|query: ")
					.append(query)
					.append("|json: ")
					.append(jsonStr)
					.toString());
		}

		String responseText = null;
		if (destination != null) {
			LOGGER.info("Create :: Destination found , create object");
			final HttpPost httpPost = ODataRequestBuilder.builder()
					.post(destination, query)
					.setContext(getContext())
					.setRequestHeader(requestParameters)
					.build();

			httpPost.setEntity(createEntityForRequest(jsonStr));

			try (final CloseableHttpClient httpclient = ODataClientBuilder.builder()
					.setContext(getContext())
					.setRequestParameters(requestParameters)
					.setDestination(destination)
					.build()) {

				responseText = httpclient.execute(httpPost, createODataResponseHandler());
			}
		} else {
			LOGGER.info("Create :: Destination not found , create object using request parameters");
			final HttpPost httpPost = ODataRequestBuilder.builder()
					.post(query)
					.setContext(getContext())
					.setRequestHeader(requestParameters)
					.build();

			httpPost.setEntity(createEntityForRequest(jsonStr));

			try (final CloseableHttpClient httpclient = ODataClientBuilder.builder()
					.setContext(getContext())
					.setRequestParameters(requestParameters)
					.build()) {

				responseText = httpclient.execute(httpPost, createODataResponseHandler());
			}
		}

		final JSONObject jsonObj = new JSONObject(responseText).getJSONObject("d");
		ToMendixSerializer.updateMendixObject(getContext(), jsonObj, odataObject.getMendixObject());

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode LOGGER = Core.getLogger(Constants.getLogNode());

	private ODataResponseHandler createODataResponseHandler() {
		return new ODataResponseHandler("CREATE", LOGGER, getContext(),
				ExpectedHttpResultOptional.ofNullable(requestParameters).orDefault(201).getExpectedHttpResult());
	}

	private HttpEntity createEntityForRequest(String jsonString) {
		return EntityBuilder.create()
				.setText(jsonString)
				.setContentType(ContentType.APPLICATION_JSON.withCharset(Consts.UTF_8))
				.build();
	}
	// END EXTRA CODE
}
