// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapodataconnector.actions;

import java.util.ArrayList;
import java.util.List;
import org.apache.http.client.methods.HttpRequestBase;
import org.apache.http.impl.client.CloseableHttpClient;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import sapodataconnector.proxies.constants.Constants;
import sapodataconnector.utils.JsonSerializer;
import sapodataconnector.utils.ODataClientBuilder;
import sapodataconnector.utils.ODataRequestBuilder;
import sapodataconnector.utils.ODataResponseHandler;
import sapodataconnector.utils.ExpectedHttpResultOptional;
import sapodataconnector.utils.HttpRequest;
import sapodataconnector.utils.ToMendixSerializer;

public class ExecuteCollection extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String responseType;
	private IMendixObject __destination;
	private sapodataconnector.proxies.Destination destination;
	private java.lang.String url;
	private sapodataconnector.proxies.HttpMethod httpMethod;
	private IMendixObject __functionParameters;
	private sapodataconnector.proxies.FunctionParameters functionParameters;
	private IMendixObject __requestParameters;
	private sapodataconnector.proxies.RequestParams requestParameters;

	public ExecuteCollection(IContext context, java.lang.String responseType, IMendixObject destination, java.lang.String url, java.lang.String httpMethod, IMendixObject functionParameters, IMendixObject requestParameters)
	{
		super(context);
		this.responseType = responseType;
		this.__destination = destination;
		this.url = url;
		this.httpMethod = httpMethod == null ? null : sapodataconnector.proxies.HttpMethod.valueOf(httpMethod);
		this.__functionParameters = functionParameters;
		this.__requestParameters = requestParameters;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.destination = __destination == null ? null : sapodataconnector.proxies.Destination.initialize(getContext(), __destination);

		this.functionParameters = __functionParameters == null ? null : sapodataconnector.proxies.FunctionParameters.initialize(getContext(), __functionParameters);

		this.requestParameters = __requestParameters == null ? null : sapodataconnector.proxies.RequestParams.initialize(getContext(), __requestParameters);

		// BEGIN USER CODE
		if(LOGGER.isDebugEnabled()) {
			LOGGER.debug(new StringBuilder(getContext().getSession().getId().toString())
					.append("|")
					.append(httpMethod)
					.append("|ExecuteCollection, url: ")
					.append(url)
					.toString());
		}

		String bodyContent = null;
		String parameterizedUrl = url;
		if (httpMethod.equals(sapodataconnector.proxies.HttpMethod.POST)
				&& (functionParameters != null && !functionParameters.getpostParameterInline())) {
			bodyContent = JsonSerializer.writeMendixObjectToJson(getContext(), __functionParameters, false).toString();
		} else {
			parameterizedUrl = HttpRequest.setGetParameters(getContext(), url, functionParameters);
		}
		
		ODataRequestBuilder.Builder builder = ODataRequestBuilder.builder();
		if (sapodataconnector.proxies.HttpMethod.POST.equals(httpMethod)) {
			builder.post(destination, parameterizedUrl)
				.setBodyContent(bodyContent);
		} else if (sapodataconnector.proxies.HttpMethod.GET.equals(httpMethod)) {
			builder.get(destination, parameterizedUrl);
		}
		
		HttpRequestBase httpRequest = builder.setContext(getContext())
			.setRequestHeader(requestParameters)
			.setBodyContent(bodyContent)
			.build();

		String response = null;
		try (final CloseableHttpClient httpClient = ODataClientBuilder.builder()
				.setContext(getContext())
				.setRequestParameters(requestParameters)
				.setDestination(destination)
				.build()){

			response = httpClient.execute(httpRequest, new ODataResponseHandler(httpMethod.toString(), LOGGER, getContext(),
					ExpectedHttpResultOptional.ofNullable(requestParameters).getExpectedHttpResult()));
		}

		final List<IMendixObject> resultList = new ArrayList<>();
		ToMendixSerializer.createNewMendixObjectList(getContext(), responseType, resultList, null, response);

		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteCollection";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode LOGGER = Core.getLogger(Constants.getLogNode());
	// END EXTRA CODE
}
